version: '3.1'
volumes:
  init_sql:
services:
  web:
    build: ./build/go
    ports:
      - "8000:8001"
    env_file: .env
  db:
    build: ./build/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - init_sql:/docker-entrypoint-initdb.d